import React, {useState, useEffect} from 'react'
import {Card,FormField,Loader} from '../components'
const Home = () => {
  const RenderCards = ({data,title}) => {
    if(data?.length>0)
    {
        return data.map((post:object) => <Card key={post._id}  {...post} />)
    }

    return (
        <h2 className='mt-5 font-bold text-[#6469ff] text-xl uppercase'>{title}</h2>
    )

  }
  const [loading,setLoading] = useState(false)
  const [allPosts,setAllPosts] = useState(null)

  const [searchText,setsearchText] = useState('')
  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
            <p className='mt-2 text-[#666375] text-[16px] max-w-[500px]'>Browse through a collection of imaginative and visually stunning images generated by Dall-E AI</p>
        </div>
        <div className='mt-16'>
            <FormField />
        </div>

        <div className='mt-10'>
            {loading ? (
                <div className='flex justify-center items-center'>
                    <Loader />
                </div>
            ):<>
                {searchText && (
                    <h2 className='font-md text-[#666375] text-xl mb-3'> Showing Result for <span className='text-[#222328]'>{searchText}</span></h2>
                )}

                <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>

                    {searchText ? (
                        <RenderCards data={[]} title="No search Results found" />
                    ):(                        <RenderCards data={[]} title="No more Posts found" />
                    )}
                </div>
            </>}
        </div>
    </section>
  )
}

export default Home